name: 'GitHub Release Actions'

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release .
      - name: Compile
        run: cmake --build . --config Release -j 2
      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        run: cmake --build . --config Release --target package
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*.deb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
