name: 'GitHub Release Actions'

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release .
      - name: Compile
        run: cmake --build . --config Release -j 2
      - name: Package
        run: cmake --build . --config Release --target package
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.${{ github.run_number }}
          files: ./*.deb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
